#!/bin/bash

# Author: Denilson Martins
# Date Created: 06/09/2021
# Last Modified: 06/09/2021

# Description
# Creates a backup in ~/github/bash_course folder of all files in the ~/github/bash_course

# Usage 
# backup_script

tar -cvf ~/github/bash_course/my_backup_"$(date +%d-%m-%Y_%H-%M-%S)".tar ~/github/bash_course 2>/dev/null

exit 0